### ISSUE TITLE
BUG: a0 term is wrong in blackman_harris window function

### ISSUE THREAD

**Issue by antimora** [yamadapc/augmented-audio#484]
Minor but leads to a wrong windowing. `a0` term is wrong in `blackman_harris` (see the line https://github.com/yamadapc/augmented-audio/blob/af08f580024039a23b0e26c0b93de8e87a927ff6/crates/augmented/audio/audio-processor-analysis/src/window_functions/mod.rs#L57) Instead of `a0 = 0.36875`, it should `a0 = 0.35875` according to :  https://en.wikipedia.org/wiki/Window_function#Blackman%E2%80%93Harris_window

**Comment by yamadapc** [comment]
Ops, thanks for reporting that, will fix in a moment

**Comment by yamadapc** [comment]
Fixed in `0.4`, :+1: :+1: https://crates.io/crates/audio-processor-analysis
