### ISSUE TITLE
Screen sleeps while Simple Metronome is playing

### ISSUE THREAD

**Issue by shamlord** [yamadapc/augmented-audio#596]
iOS 16.2, iPhone 14

Issue: If the start button is pressed and a beat is playing, the phone screen went to sleep in accordance with the device settings, stopping the beat.

Expected Behavior: If the metronome is stopped, the device screen should be permitted to sleep. If the metronome is started, the device screen should be prevented from sleeping.

**Comment by yamadapc** [comment]
I'll address this on the next release, should be fairly straightforward with https://pub.dev/packages/wakelock
