### ISSUE TITLE
No sound from Simple Metronome when iPhone ringer off

### ISSUE THREAD

**Issue by rectang** [yamadapc/augmented-audio#607]
If the ringer switch for an iPhone is turned off, Simple Metronome won't make any sound and won't give any indication of why.

I speculate that this may be the issue that `stephane.clement` ran into, described in the "There's no sound in the app" review from 2022-11-17 for the iPhone Simple Metronome app.

Proposed resolution: play sound while the ringer switch is set to off, similar to the behavior of other audio apps (e.g. Spotify).

**Comment by yamadapc** [comment]
Thank you for this report. I will look into this and address it.

**Comment by yamadapc** [comment]
Something like:

```swift
func configureAudioSession() {
  let audioSession = AVAudioSession.sharedInstance()
  do {
    // Set the audio session category and mode.
    try audioSession.setCategory(.playback, mode: .default, options: [.mixWithOthers])
  } catch {
    print("Failed to set the audio session configuration")
  }
}
```
